FROM lambci/lambda:build-nodejs6.10

RUN apk update && apk add yarn

WORKDIR /repo

# Install dependencies for the mounted project, so that
# the dependencies of the deploy script are satisfied.
CMD yarn && yarn deploy
