FROM ubuntu:16.04

# Install prerequisites
RUN apt-get update && apt-get upgrade -y

RUN apt-get install -y curl openssl lsb-release

# Add Node.js source
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -

# Add yarn source
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

# Add the Cloud SDK distribution URI as a package source
RUN \
  export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)" \
  && \
  echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | \
    tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

# Import the Google Cloud public key
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

RUN apt-get update
RUN apt-get install google-cloud-sdk nodejs yarn git -y

RUN mkdir /repo

WORKDIR /repo

# Install dependencies for the mounted project, so that
# the dependencies of the deploy script are satisfied.
CMD yarn --prod && node deploy.js
