FROM lambci/lambda:build-nodejs6.10

RUN npm i --global @babel/core @babel/node

WORKDIR /repo

# Install dependencies for the mounted project, so that
# the dependencies of the deploy script are satisfied.
CMD npm i && babel-node deploy.js
